#page title
page_title: Trilby for Hacker News # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1234793120 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
  https://emilbaehr.com # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Trilby for Hacker News # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Free # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: The best way to experience Hacker News on Android. Coming soon to iOS.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Faisal Ahmed
your_link: https://faisalbin.com
your_city: Munich
email_address: dev@faisalbin.com
facebook_username:
instagram_username:
twitter_username: FaisalBAhmed
github_username: faisalbinahmed
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: See What's Happening in Hacker News
    description: Read the top and latest posts from HN, and many more.
    fontawesome_icon_name: newspaper

  - title: Dark Mode
    description: Dark mode for your night time viewing. Can automatically sync with your system.
    fontawesome_icon_name: moon

  - title: Beautifully Crafted Skins
    description: Six meticulously picked color skins. Pick whichever you like and sync with Light/Dark Mode.
    fontawesome_icon_name: palette

  - title: Powerful Search Features
    description: Search HN posts powered by Algolia - just like the HN web. Sort by date, and filter by post type.
    fontawesome_icon_name: search

  - title: Highly Customizable
    description: Make the app look like the way you want.
    fontawesome_icon_name: tools

  - title: Read History
    description: Keep track of your last read articles.
    fontawesome_icon_name: history

  - title: Profile View
    description: View yours and others' profile and their latest activities.
    fontawesome_icon_name: address-card

  - title: Read Comments in Great Details
    description: Trilby was created with reading comments in mind. If you're like me who uses HN mainly to read comments, Trilby is the app for you.
    fontawesome_icon_name: book

  - title: Login Functions
    description: Use features like commenting, upvoting, and posting new stories that require you to login right from the app.
    fontawesome_icon_name: edit

  - title: Native Links Support
    description: Open and read native HN links within the app itself. Look out for that Orange link.
    fontawesome_icon_name: paperclip # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
